application:
  title: CascadiaFest
  url: http://localhost
  email: info@cascadiajs.com
  eventurl: http://localhost
  event_location: Washington State, USA
  enddate: Oct. 14th, 2016
  show_submission_count: false
  airport: MIA
  arrival: 2014-10-26
  departure: 2014-10-31
  secure_ssl: false
  online_conference: false
  date_format: m ([ .\t-])* dd [,.stndrh\t ]+ y


api:
  enabled: true

cache:
  enabled: false

database:
  host: 127.0.0.1
  database: cfp
  dsn: mysql:dbname=cfp;host=127.0.0.1
  user: root
  password: ~

log:
  level: debug

mail:
  host: ~
  port: ~
  username: ~
  password: ~
  encryption: ~
  auth_mode: ~
